In [2]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Display wider tables
pd.set_option("display.width", 1000)

In [3]:
file_path = "../data/raw/online_retail_II.xlsx"

df = pd.read_excel(file_path)

df.head()

  Invoice StockCode                          Description  Quantity         InvoiceDate  Price  Customer ID         Country
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12 2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1  489434    79323P                   PINK CHERRY LIGHTS        12 2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2  489434    79323W                  WHITE CHERRY LIGHTS        12 2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48 2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24 2009-12-01 07:45:00   1.25      13085.0  United Kingdom

In [4]:
# Display the number of rows and columns
print(f"Dataset Shape: {df.shape}")

print("\n")

# Display column names
print("Columns:")
print(df.columns.tolist())

print("\n")

# Display data types
print("Data Types:")
print(df.dtypes)

Dataset Shape: (525461, 8)


Columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']


Data Types:
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [6]:
# Count missing values in each column
missing_values = df.isnull().sum()

# Calculate percentage of missing values
missing_percentage = (missing_values / len(df)) * 100

# Create a summary table
missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage": missing_percentage.round(2)
})

# Display only columns with missing values
missing_summary[missing_summary["Missing Values"] > 0]

             Missing Values  Percentage
Description            2928        0.56
Customer ID          107927       20.54

In [7]:
# Count missing values in each column
missing_values = df.isnull().sum()

# Calculate percentage of missing values
missing_percentage = (missing_values / len(df)) * 100

# Create a summary table
missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage": missing_percentage.round(2)
})

# Display only columns with missing values
missing_summary[missing_summary["Missing Values"] > 0]

             Missing Values  Percentage
Description            2928        0.56
Customer ID          107927       20.54

In [8]:
# Generate descriptive statistics for numerical columns
df.describe()

            Quantity                 InvoiceDate          Price    Customer ID
count  525461.000000                      525461  525461.000000  417534.000000
mean       10.337667  2010-06-28 11:37:36.845018       4.688834   15360.645478
min     -9600.000000         2009-12-01 07:45:00  -53594.360000   12346.000000
25%         1.000000         2010-03-21 12:20:00       1.250000   13983.000000
50%         3.000000         2010-07-06 09:51:00       2.100000   15311.000000
75%        10.000000         2010-10-15 12:45:00       4.210000   16799.000000
max     19152.000000         2010-12-09 20:01:00   25111.090000   18287.000000
std       107.424110                         NaN     146.126914    1680.811316

In [9]:
# Generate descriptive statistics for all columns
df.describe(include='all')

         Invoice StockCode                         Description       Quantity                 InvoiceDate          Price    Customer ID         Country
count   525461.0    525461                              522533  525461.000000                      525461  525461.000000  417534.000000          525461
unique   28816.0      4632                                4681            NaN                         NaN            NaN            NaN              40
top     537434.0    85123A  WHITE HANGING HEART T-LIGHT HOLDER            NaN                         NaN            NaN            NaN  United Kingdom
freq       675.0      3516                                3549            NaN                         NaN            NaN            NaN          485852
mean         NaN       NaN                                 NaN      10.337667  2010-06-28 11:37:36.845018       4.688834   15360.645478             NaN
min          NaN       NaN                                 NaN   -9600.000000         2009-12-01 07:45:00  -53594.360000   12346.000000             NaN
25%          NaN       NaN                                 NaN       1.000000         2010-03-21 12:20:00       1.250000   13983.000000             NaN
50%          NaN       NaN                                 NaN       3.000000         2010-07-06 09:51:00       2.100000   15311.000000             NaN
75%          NaN       NaN                                 NaN      10.000000         2010-10-15 12:45:00       4.210000   16799.000000             NaN
max          NaN       NaN                                 NaN   19152.000000         2010-12-09 20:01:00   25111.090000   18287.000000             NaN
std          NaN       NaN                                 NaN     107.424110                         NaN     146.126914    1680.811316             NaN

# Data Dictionary

| Column | Data Type | Description | Business Meaning |
|--------|-----------|-------------|------------------|
| Invoice | Object | Invoice number | Unique transaction identifier (may repeat for multiple items in one order) |
| StockCode | Object | Product code | Unique identifier for each product |
| Description | Object | Product description | Human-readable product name |
| Quantity | Integer | Quantity sold | Number of units purchased (negative values may indicate returns) |
| InvoiceDate | Datetime | Transaction timestamp | Date and time when the invoice was created |
| Price | Float | Unit price | Price per individual item |
| Customer ID | Float | Customer identifier | Unique customer ID (contains missing values) |
| Country | Object | Customer country | Country where the customer is located |

# Data Dictionary

| Column | Data Type | Description | Business Meaning |
|--------|-----------|-------------|------------------|
| Invoice | Object | Invoice number | Unique transaction identifier (may repeat for multiple items in one order) |
| StockCode | Object | Product code | Unique identifier for each product |
| Description | Object | Product description | Human-readable product name |
| Quantity | Integer | Quantity sold | Number of units purchased (negative values may indicate returns) |
| InvoiceDate | Datetime | Transaction timestamp | Date and time when the invoice was created |
| Price | Float | Unit price | Price per individual item |
| Customer ID | Float | Customer identifier | Unique customer ID (contains missing values) |
| Country | Object | Customer country | Country where the customer is located |

In [11]:
# Check for duplicate rows
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 6865

In [12]:
# Display duplicate rows (first 10)
df[df.duplicated()].head(10)

    Invoice StockCode                        Description  Quantity         InvoiceDate  Price  Customer ID         Country
371  489517     21912           VINTAGE SNAKES & LADDERS         1 2009-12-01 11:34:00   3.75      16329.0  United Kingdom
383  489517     22130   PARTY CONE CHRISTMAS DECORATION          6 2009-12-01 11:34:00   0.85      16329.0  United Kingdom
384  489517     22319  HAIRCLIPS FORTIES FABRIC ASSORTED        12 2009-12-01 11:34:00   0.65      16329.0  United Kingdom
385  489517     21913     VINTAGE SEASIDE JIGSAW PUZZLES         1 2009-12-01 11:34:00   3.75      16329.0  United Kingdom
386  489517     21821   GLITTER STAR GARLAND WITH BELLS          1 2009-12-01 11:34:00   3.75      16329.0  United Kingdom
390  489517    84951A    S/4 PISTACHIO LOVEBIRD COASTERS         1 2009-12-01 11:34:00   2.55      16329.0  United Kingdom
391  489517     21491    SET OF THREE VINTAGE GIFT WRAPS         1 2009-12-01 11:34:00   1.95      16329.0  United Kingdom
394  489517     21912           VINTAGE SNAKES & LADDERS         1 2009-12-01 11:34:00   3.75      16329.0  United Kingdom
657  489529     22028       PENNY FARTHING BIRTHDAY CARD        12 2009-12-01 11:51:00   0.42      17984.0  United Kingdom
658  489529     22036             DINOSAUR BIRTHDAY CARD        12 2009-12-01 11:51:00   0.42      17984.0  United Kingdom

In [13]:
# Count transactions with negative quantities
negative_quantity = df[df["Quantity"] < 0]

print(f"Negative quantity transactions: {len(negative_quantity)}")

Negative quantity transactions: 12326

In [14]:
# View the first 10 negative quantity transactions
negative_quantity.head(10)

     Invoice StockCode                        Description  Quantity         InvoiceDate  Price  Customer ID         Country
178  C489449     22087           PAPER BUNTING WHITE LACE       -12 2009-12-01 10:33:00   2.95      16321.0       Australia
179  C489449    85206A       CREAM FELT EASTER EGG BASKET        -6 2009-12-01 10:33:00   1.65      16321.0       Australia
180  C489449     21895      POTTING SHED SOW 'N' GROW SET        -4 2009-12-01 10:33:00   4.25      16321.0       Australia
181  C489449     21896                 POTTING SHED TWINE        -6 2009-12-01 10:33:00   2.10      16321.0       Australia
182  C489449     22083         PAPER CHAIN KIT RETRO SPOT       -12 2009-12-01 10:33:00   2.95      16321.0       Australia
183  C489449     21871                SAVE THE PLANET MUG       -12 2009-12-01 10:33:00   1.25      16321.0       Australia
184  C489449     84946    ANTIQUE SILVER TEA GLASS ETCHED       -12 2009-12-01 10:33:00   1.25      16321.0       Australia
185  C489449    84970S  HANGING HEART ZINC T-LIGHT HOLDER       -24 2009-12-01 10:33:00   0.85      16321.0       Australia
186  C489449     22090          PAPER BUNTING RETRO SPOTS       -12 2009-12-01 10:33:00   2.95      16321.0       Australia
196  C489459    90200A         PURPLE SWEETHEART BRACELET        -3 2009-12-01 10:44:00   4.25      17592.0  United Kingdom

In [15]:
# Business Check:
# Returns and cancellations are often recorded as negative quantities.
# We investigate them instead of removing them because they contribute
# to revenue leakage.

negative_quantity = df[df["Quantity"] < 0]

In [16]:
# Business Check:
# Negative prices are unusual in retail transactions.
# We investigate them before deciding whether they are
# valid accounting entries or data quality issues.

negative_price = df[df["Price"] < 0]

print(f"Negative price transactions: {len(negative_price)}")

Negative price transactions: 3

In [17]:
negative_price.head(10)

        Invoice StockCode      Description  Quantity         InvoiceDate     Price  Customer ID         Country
179403  A506401         B  Adjust bad debt         1 2010-04-29 13:36:00 -53594.36          NaN  United Kingdom
276274  A516228         B  Adjust bad debt         1 2010-07-19 11:24:00 -44031.79          NaN  United Kingdom
403472  A528059         B  Adjust bad debt         1 2010-10-20 12:04:00 -38925.87          NaN  United Kingdom