# Revenue Leakage & Cohort Churn Analysis

## Notebook Objective

Create analytical features that simplify business analysis and dashboard development.

## Features to Create

- Revenue
- Invoice Year
- Invoice Month
- Year-Month
- Invoice Day
- Invoice Hour

In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

In [4]:
# Load raw dataset
file_path = "../data/raw/online_retail_II.xlsx"

df = pd.read_excel(file_path)

# Remove duplicates
df = df.drop_duplicates(ignore_index=True)

# Remove accounting adjustment entries
df = df[df["Description"] != "Adjust bad debt"].reset_index(drop=True)

# Remove missing descriptions
df = df.dropna(subset=["Description"]).reset_index(drop=True)

print(f"Dataset ready for feature engineering: {df.shape}")

Dataset ready for feature engineering: (515665, 8)

In [5]:
# Business Feature:
# Revenue represents the monetary value of each transaction.
# Returns automatically become negative revenue because
# returned quantities are stored as negative values.

df["Revenue"] = df["Quantity"] * df["Price"]

print("Revenue column created successfully.")

Revenue column created successfully.

In [6]:
df[[
    "Quantity",
    "Price",
    "Revenue"
]].head(10)

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0
5        24   1.65     39.6
6        24   1.25     30.0
7        10   5.95     59.5
8        12   2.55     30.6
9        12   3.75     45.0

In [7]:
df["Revenue"] = df["Quantity"] + df["Price"]

In [8]:
# Recreate the Revenue column correctly
df["Revenue"] = df["Quantity"] * df["Price"]

print("Revenue column corrected successfully.")

Revenue column corrected successfully.

In [9]:
df[["Quantity", "Price", "Revenue"]].head(10)

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0
5        24   1.65     39.6
6        24   1.25     30.0
7        10   5.95     59.5
8        12   2.55     30.6
9        12   3.75     45.0

In [10]:
# Business Feature:
# Extract the year of each transaction for yearly trend analysis.

df["Invoice Year"] = df["InvoiceDate"].dt.year

print("Invoice Year feature created successfully.")

Invoice Year feature created successfully.

In [11]:
df[["InvoiceDate", "Invoice Year"]].head(10)

          InvoiceDate  Invoice Year
0 2009-12-01 07:45:00          2009
1 2009-12-01 07:45:00          2009
2 2009-12-01 07:45:00          2009
3 2009-12-01 07:45:00          2009
4 2009-12-01 07:45:00          2009
5 2009-12-01 07:45:00          2009
6 2009-12-01 07:45:00          2009
7 2009-12-01 07:45:00          2009
8 2009-12-01 07:46:00          2009
9 2009-12-01 07:46:00          2009

In [12]:
# Business Feature:
# Extract the transaction month for monthly trend analysis.

df["Invoice Month"] = df["InvoiceDate"].dt.month

print("Invoice Month feature created successfully.")

Invoice Month feature created successfully.

In [13]:
df[["InvoiceDate", "Invoice Month"]].head(10)

          InvoiceDate  Invoice Month
0 2009-12-01 07:45:00             12
1 2009-12-01 07:45:00             12
2 2009-12-01 07:45:00             12
3 2009-12-01 07:45:00             12
4 2009-12-01 07:45:00             12
5 2009-12-01 07:45:00             12
6 2009-12-01 07:45:00             12
7 2009-12-01 07:45:00             12
8 2009-12-01 07:46:00             12
9 2009-12-01 07:46:00             12

In [14]:
# Business Feature:
# Combine year and month into a single feature for monthly trend analysis.

df["Year-Month"] = df["InvoiceDate"].dt.to_period("M").astype(str)

print("Year-Month feature created successfully.")

Year-Month feature created successfully.

In [15]:
df[["InvoiceDate", "Invoice Year", "Invoice Month", "Year-Month"]].head(10)

          InvoiceDate  Invoice Year  Invoice Month Year-Month
0 2009-12-01 07:45:00          2009             12    2009-12
1 2009-12-01 07:45:00          2009             12    2009-12
2 2009-12-01 07:45:00          2009             12    2009-12
3 2009-12-01 07:45:00          2009             12    2009-12
4 2009-12-01 07:45:00          2009             12    2009-12
5 2009-12-01 07:45:00          2009             12    2009-12
6 2009-12-01 07:45:00          2009             12    2009-12
7 2009-12-01 07:45:00          2009             12    2009-12
8 2009-12-01 07:46:00          2009             12    2009-12
9 2009-12-01 07:46:00          2009             12    2009-12

In [16]:
# Business Feature:
# Extract the day of the month for daily transaction analysis.

df["Invoice Day"] = df["InvoiceDate"].dt.day

print("Invoice Day feature created successfully.")

Invoice Day feature created successfully.

In [17]:
df[["InvoiceDate", "Invoice Day"]].head(10)

          InvoiceDate  Invoice Day
0 2009-12-01 07:45:00            1
1 2009-12-01 07:45:00            1
2 2009-12-01 07:45:00            1
3 2009-12-01 07:45:00            1
4 2009-12-01 07:45:00            1
5 2009-12-01 07:45:00            1
6 2009-12-01 07:45:00            1
7 2009-12-01 07:45:00            1
8 2009-12-01 07:46:00            1
9 2009-12-01 07:46:00            1

In [18]:
# Business Feature:
# Extract the transaction hour for hourly sales pattern analysis.

df["Invoice Hour"] = df["InvoiceDate"].dt.hour

print("Invoice Hour feature created successfully.")

Invoice Hour feature created successfully.

In [19]:
df[["InvoiceDate", "Invoice Hour"]].head(10)

          InvoiceDate  Invoice Hour
0 2009-12-01 07:45:00             7
1 2009-12-01 07:45:00             7
2 2009-12-01 07:45:00             7
3 2009-12-01 07:45:00             7
4 2009-12-01 07:45:00             7
5 2009-12-01 07:45:00             7
6 2009-12-01 07:45:00             7
7 2009-12-01 07:45:00             7
8 2009-12-01 07:46:00             7
9 2009-12-01 07:46:00             7

In [20]:
# Save the cleaned and feature-engineered dataset

output_path = "../data/cleaned/online_retail_cleaned.csv"

df.to_csv(output_path, index=False)

print(f"Dataset saved successfully to:\n{output_path}")

Dataset saved successfully to:
../data/cleaned/online_retail_cleaned.csv

In [21]:
import os

os.path.exists(output_path)

True